# Generated by Django 5.2.17 on 2026-09-16 17:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Policy product name, e.g. Star Comprehensive",
                        max_length=255,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Insurance company name, e.g. Star Health, HDFC ERGO, Care Health",
                        max_length=255,
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual Health"),
                            ("FAMILY_FLOATER", "Family Floater"),
                            ("SENIOR_CITIZEN", "Senior Citizen"),
                            ("CRITICAL_ILLNESS", "Critical Illness"),
                            ("TOP_UP", "Top-up / Super Top-up"),
                            ("GROUP", "Group Health Insurance"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="INDIVIDUAL",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("ANALYZED", "Analyzed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="policy_user_created_idx"
                    ),
                    models.Index(
                        fields=["provider", "policy_type"], name="policy_prov_type_idx"
                    ),
                ],
            },
        ),
    ]
