# Generated by Django 5.2.17 on 2026-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_alter_policy_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Diagnostic failure message if analysis failed",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="premium",
            field=models.CharField(
                blank=True, help_text="e.g. ₹18,500", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="sum_insured",
            field=models.CharField(
                blank=True, help_text="e.g. ₹10,00,000", max_length=100, null=True
            ),
        ),
    ]
