# Generated by Django 5.2.17 on 2026-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_policy_error_message_policy_policy_period_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                choices=[
                    ("INDIVIDUAL", "Individual Health"),
                    ("FAMILY_FLOATER", "Family Floater"),
                    ("SENIOR_CITIZEN", "Senior Citizen"),
                    ("CRITICAL_ILLNESS", "Critical Illness"),
                    ("TOP_UP", "Top-up / Super Top-up"),
                    ("GROUP", "Group Health Insurance"),
                    ("HEALTH", "Health Insurance"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="INDIVIDUAL",
                max_length=50,
            ),
        ),
    ]
