# Generated by Django 5.2.17 on 2026-09-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0004_alter_policy_policy_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                choices=[
                    ("INDIVIDUAL", "Individual Health"),
                    ("FAMILY_FLOATER", "Family Floater"),
                    ("SENIOR_CITIZEN", "Senior Citizen"),
                    ("CRITICAL_ILLNESS", "Critical Illness"),
                    ("TOP_UP", "Top-up / Super Top-up"),
                    ("GROUP", "Group Health Insurance"),
                    ("HEALTH", "Health Insurance"),
                    ("LIFE", "Life Insurance"),
                    ("TERM_LIFE", "Term Life Insurance"),
                    ("MOTOR", "Motor Insurance"),
                    ("CAR", "Car Insurance"),
                    ("BIKE", "Two-Wheeler / Bike Insurance"),
                    ("TRAVEL", "Travel Insurance"),
                    ("HOME", "Home Insurance"),
                    ("PROPERTY", "Property Insurance"),
                    ("PERSONAL_ACCIDENT", "Personal Accident Insurance"),
                    ("CORPORATE", "Corporate Insurance"),
                    ("COMMERCIAL", "Commercial / SME Insurance"),
                    ("OTHER", "Other Insurance"),
                ],
                db_index=True,
                default="INDIVIDUAL",
                max_length=50,
            ),
        ),
    ]
