# Generated by Django 5.2.17 on 2026-09-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("PENDING", "Pending"),
                    ("EXTRACTING", "Extracting Text"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="UPLOADED",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["policy", "file_hash"], name="doc_policy_hash_idx"
            ),
        ),
    ]
