# Generated by Django 5.2.17 on 2026-09-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0002_document_file_hash_alter_document_processing_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="error_message",
            field=models.TextField(
                blank=True, default="", help_text="Safe error details if failed"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("PROCESSING", "Processing"),
                    ("EXTRACTING", "Extracting Text"),
                    ("OCR", "OCR Processing"),
                    ("CHUNKING", "Chunking Document"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="UPLOADED",
                max_length=50,
            ),
        ),
    ]
