# Generated by Django 5.2.17 on 2026-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_error_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("EXTRACTING", "Extracting Text"),
                    ("OCR", "OCR Processing"),
                    ("CHUNKING", "Chunking Document"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="UPLOADED",
                max_length=50,
            ),
        ),
    ]
