# Generated by Django 5.2.17 on 2026-09-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEXT_PDF", "Digital Text PDF"),
                    ("SCANNED_PDF", "Scanned Image PDF"),
                    ("MIXED_PDF", "Mixed Text & Images"),
                    ("LOW_TEXT", "Low Text Density"),
                    ("OCR_REQUIRED", "OCR Required"),
                    ("UNREADABLE", "Unreadable"),
                ],
                db_index=True,
                default="TEXT_PDF",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="documentpage",
            name="cleaned_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Normalized text preserving layout and structure",
            ),
        ),
        migrations.AddField(
            model_name="documentpage",
            name="raw_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Raw uncleaned text extracted from page",
            ),
        ),
        migrations.AlterField(
            model_name="documentpage",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Extracted text (synced with cleaned_text)",
            ),
        ),
    ]
