# Generated by Django 5.2.17 on 2026-09-16 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COVERAGE", "Coverage"),
                            ("EXCLUSION", "Exclusion"),
                            ("WAITING_PERIOD", "Waiting Period"),
                            ("DEDUCTIBLE", "Deductible / Co-pay"),
                            ("LIMIT", "Sub-limit / Capping"),
                            ("CONDITION", "Condition"),
                            ("CLAIM_REQUIREMENT", "Claim Requirement"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short descriptor, e.g. Pre-existing disease waiting period",
                        max_length=255,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Simple plain-language summary for consumers"
                    ),
                ),
                (
                    "source_text",
                    models.TextField(
                        help_text="Verbatim quote from original policy document"
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Page number where the clause appears in the PDF",
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Policy section or heading title, e.g. Section 4.1",
                        max_length=255,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="Extraction confidence score between 0.0 and 1.0",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clause",
                "verbose_name_plural": "Clauses",
                "ordering": ["policy", "category", "page_number"],
                "indexes": [
                    models.Index(
                        fields=["policy", "category"], name="clause_policy_cat_idx"
                    ),
                    models.Index(
                        fields=["policy", "page_number"], name="clause_policy_page_idx"
                    ),
                ],
            },
        ),
    ]
