# Generated by Django 5.2.17 on 2026-09-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clauses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clause",
            name="category",
            field=models.CharField(
                choices=[
                    ("COVERAGE", "Coverage"),
                    ("EXCLUSION", "Exclusion"),
                    ("WAITING_PERIOD", "Waiting Period"),
                    ("DEDUCTIBLE", "Deductible / Co-pay"),
                    ("LIMIT", "Sub-limit / Capping"),
                    ("CONDITION", "Condition"),
                    ("CLAIM_REQUIREMENT", "Claim Requirement"),
                    ("ELIGIBILITY", "Eligibility"),
                    ("PREMIUM", "Premium"),
                    ("SUM_INSURED", "Sum Insured / Limit of Liability"),
                    ("POLICY_PERIOD", "Policy Period / Term"),
                    ("RENEWAL", "Renewal"),
                    ("CANCELLATION", "Cancellation"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
